# Generated by Django 4.2.7 on 2025-08-20 15:29

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0002_loanapplication_certificate_generated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRNSystemReserve',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_prn_issued', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=18)),
                ('total_usd_backing', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('prn_in_circulation', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=18)),
                ('prn_pledged_total', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=18)),
                ('backing_ratio', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=5)),
                ('last_audit_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PRNWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=18)),
                ('pledged_balance', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=18)),
                ('available_balance', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=18)),
                ('wallet_address', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prn_wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PRNTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_hash', models.CharField(max_length=128, unique=True)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('transaction_type', models.CharField(choices=[('issue', 'Issue PRN (Loan Disbursement)'), ('pledge', 'Pledge PRN (Loan Collateral)'), ('unpledge', 'Unpledge PRN (Loan Repayment)'), ('transfer', 'Transfer PRN'), ('burn', 'Burn PRN (System)')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reference_id', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('from_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transactions', to='pronova.prnwallet')),
                ('to_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transactions', to='pronova.prnwallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ElectronicCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_number', models.CharField(max_length=50, unique=True)),
                ('prn_amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('usd_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pledged', 'Pledged to Nova'), ('released', 'Released'), ('expired', 'Expired')], default='active', max_length=20)),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField()),
                ('pledge_release_date', models.DateTimeField(blank=True, null=True)),
                ('capimax_certificate_id', models.CharField(blank=True, max_length=255)),
                ('capimax_investment_active', models.BooleanField(default=False)),
                ('pdf_generated', models.BooleanField(default=False)),
                ('pdf_file_path', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='loans.loanapplication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CapimaxInvestment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('capimax_investment_id', models.CharField(max_length=255, unique=True)),
                ('capimax_profile_id', models.CharField(max_length=255)),
                ('investment_amount_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('investment_type', models.CharField(max_length=100)),
                ('current_profit_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_profit_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('last_profit_update', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active Investment'), ('completed', 'Investment Completed'), ('withdrawn', 'Investment Withdrawn'), ('paused', 'Investment Paused')], default='active', max_length=20)),
                ('started_date', models.DateTimeField(auto_now_add=True)),
                ('ended_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capimax_investment', to='pronova.electroniccertificate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capimax_investments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
