# Generated by Django 4.2.7 on 2025-08-20 15:29

from decimal import Decimal
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WalletService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_name', models.CharField(default='Nova PRN Service', max_length=100)),
                ('total_prn_supply', models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=18)),
                ('total_usd_reserves', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('service_wallet_address', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
