# Generated by Django 4.2.7 on 2025-08-21 12:06

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0002_loanapplication_certificate_generated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentPlatform',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('platform_type', models.CharField(choices=[('cryptocurrency', 'Cryptocurrency Platform'), ('forex', 'Forex Trading'), ('stocks', 'Stock Market'), ('commodities', 'Commodities'), ('mixed', 'Mixed Assets')], max_length=20)),
                ('description', models.TextField()),
                ('website_url', models.URLField()),
                ('api_endpoint', models.URLField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('min_investment_usd', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('max_investment_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('commission_rate', models.DecimalField(decimal_places=4, help_text='Commission rate as decimal (e.g., 0.001 for 0.1%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('1'))])),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Under Maintenance'), ('suspended', 'Suspended'), ('beta', 'Beta Testing')], default='active', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('supports_certificates', models.BooleanField(default=True)),
                ('api_key_required', models.BooleanField(default=True)),
                ('webhook_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position_id', models.CharField(help_text='Platform-specific position ID', max_length=255)),
                ('asset_symbol', models.CharField(max_length=20)),
                ('asset_name', models.CharField(max_length=255)),
                ('position_type', models.CharField(choices=[('long', 'Long Position'), ('short', 'Short Position'), ('neutral', 'Neutral')], default='long', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('pending', 'Pending'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('investment_amount_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_value_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=16)),
                ('current_price', models.DecimalField(decimal_places=8, default=Decimal('0.00'), max_digits=16)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=16)),
                ('unrealized_pnl_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('realized_pnl_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('opened_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='UserInvestmentAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform_user_id', models.CharField(max_length=255)),
                ('platform_username', models.CharField(blank=True, max_length=255)),
                ('verification_status', models.CharField(choices=[('pending', 'Verification Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('api_key', models.TextField(blank=True, help_text='Encrypted API key')),
                ('api_secret', models.TextField(blank=True, help_text='Encrypted API secret')),
                ('balance_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('available_balance_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.investmentplatform')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='InvestmentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(help_text='Platform-specific transaction ID', max_length=255)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('buy', 'Buy Order'), ('sell', 'Sell Order'), ('dividend', 'Dividend Payment'), ('fee', 'Platform Fee'), ('commission', 'Commission')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('asset_symbol', models.CharField(blank=True, max_length=20)),
                ('quantity', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('executed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='investments.userinvestmentaccount')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investments.investmentposition')),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
        migrations.AddField(
            model_name='investmentposition',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='investments.userinvestmentaccount'),
        ),
        migrations.AddField(
            model_name='investmentposition',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loans.loan'),
        ),
        migrations.CreateModel(
            name='InvestmentAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('price_target', 'Price Target Reached'), ('stop_loss', 'Stop Loss Triggered'), ('take_profit', 'Take Profit Triggered'), ('margin_call', 'Margin Call'), ('deposit_required', 'Deposit Required'), ('withdrawal_completed', 'Withdrawal Completed'), ('position_closed', 'Position Closed')], max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('trigger_price', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True)),
                ('trigger_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('sms_sent', models.BooleanField(default=False)),
                ('triggered_at', models.DateTimeField()),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investments.userinvestmentaccount')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investments.investmentposition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='CapimaxIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('capimax_user_id', models.CharField(max_length=255, unique=True)),
                ('preferred_strategy', models.CharField(choices=[('conservative', 'Conservative Growth'), ('moderate', 'Moderate Growth'), ('aggressive', 'Aggressive Growth'), ('income', 'Income Focused'), ('balanced', 'Balanced Portfolio')], default='balanced', max_length=20)),
                ('max_investment_percentage', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Maximum percentage of loan amount to invest', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('stop_loss_percentage', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Stop loss percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1.00')), django.core.validators.MaxValueValidator(Decimal('50.00'))])),
                ('take_profit_percentage', models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Take profit percentage', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('5.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('auto_invest_enabled', models.BooleanField(default=False)),
                ('auto_invest_amount_usd', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('api_key', models.TextField(blank=True, help_text='Encrypted Capimax API key')),
                ('webhook_secret', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Capimax Integration',
                'verbose_name_plural': 'Capimax Integrations',
            },
        ),
    ]
