# Generated by Django 4.2.7 on 2025-08-20 07:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('logo_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('whitepaper_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeframe', models.CharField(choices=[('1m', '1 Minute'), ('5m', '5 Minutes'), ('15m', '15 Minutes'), ('30m', '30 Minutes'), ('1h', '1 Hour'), ('4h', '4 Hours'), ('1d', '1 Day'), ('1w', '1 Week'), ('1M', '1 Month')], max_length=3)),
                ('open_price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('high_price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('low_price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('close_price', models.DecimalField(decimal_places=8, max_digits=18)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=20)),
                ('timestamp', models.DateTimeField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='currencies.currency')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('currency', 'timeframe', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('high_24h', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('low_24h', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('change_24h_percent', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('volume_24h', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('source', models.CharField(default='manual', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to='currencies.currency')),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('currency', 'timestamp')},
            },
        ),
    ]
