# Generated by Django 4.2.7 on 2025-08-20 16:12

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pronova', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapimaxAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('capimax_account_id', models.CharField(max_length=255, unique=True)),
                ('capimax_user_id', models.CharField(max_length=255)),
                ('account_status', models.CharField(choices=[('pending', 'Pending Verification'), ('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('total_capacity_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('available_capacity_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invested_amount_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_profits_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_losses_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_profit_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capimax_account', to='pronova.electroniccertificate')),
            ],
        ),
        migrations.CreateModel(
            name='CapimaxInvestment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('investment_id', models.CharField(max_length=50, unique=True)),
                ('capimax_investment_id', models.CharField(max_length=255)),
                ('investment_type', models.CharField(choices=[('forex', 'Forex Trading'), ('stocks', 'Stock Market'), ('commodities', 'Commodities'), ('crypto', 'Cryptocurrency'), ('bonds', 'Government Bonds'), ('mutual_funds', 'Mutual Funds'), ('real_estate', 'Real Estate'), ('mixed_portfolio', 'Mixed Portfolio')], max_length=30)),
                ('investment_name', models.CharField(max_length=200)),
                ('invested_amount_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_value_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('profit_loss_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('profit_loss_percentage', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField()),
                ('expected_completion_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('very_high', 'Very High Risk')], default='medium', max_length=20)),
                ('expected_return_percentage', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('investment_description', models.TextField(blank=True)),
                ('investment_terms', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='capimax.capimaxaccount')),
            ],
        ),
        migrations.CreateModel(
            name='CapimaxPlatform',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform_name', models.CharField(default='Capimax', max_length=100)),
                ('api_base_url', models.URLField(default='https://api.capimax.com/v1/')),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('api_secret', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('accepts_nova_certificates', models.BooleanField(default=True)),
                ('minimum_investment_usd', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=12)),
                ('maximum_investment_usd', models.DecimalField(decimal_places=2, default=Decimal('50000.00'), max_digits=12)),
                ('platform_fee_percentage', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=5)),
                ('nova_commission_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('auto_sync_enabled', models.BooleanField(default=True)),
                ('sync_interval_minutes', models.PositiveIntegerField(default=60)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CapimaxTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=50, unique=True)),
                ('capimax_transaction_id', models.CharField(blank=True, max_length=255)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit to Investment'), ('withdrawal', 'Withdrawal from Investment'), ('profit_distribution', 'Profit Distribution'), ('loss_realization', 'Loss Realization'), ('fee_payment', 'Fee Payment'), ('dividend', 'Dividend Payment'), ('interest', 'Interest Payment')], max_length=30)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee_amount_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_amount_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('transaction_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='capimax.capimaxaccount')),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='capimax.capimaxinvestment')),
            ],
        ),
        migrations.CreateModel(
            name='CapimaxAPILog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('log_type', models.CharField(choices=[('account_creation', 'Account Creation'), ('investment_create', 'Investment Creation'), ('investment_update', 'Investment Update'), ('profit_sync', 'Profit Synchronization'), ('transaction_sync', 'Transaction Sync'), ('status_check', 'Status Check'), ('error_handling', 'Error Handling')], max_length=30)),
                ('endpoint', models.CharField(max_length=255)),
                ('http_method', models.CharField(max_length=10)),
                ('request_data', models.JSONField(default=dict)),
                ('response_data', models.JSONField(default=dict)),
                ('status_code', models.PositiveIntegerField()),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('request_at', models.DateTimeField(auto_now_add=True)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_logs', to='capimax.capimaxaccount')),
                ('investment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_logs', to='capimax.capimaxinvestment')),
            ],
            options={
                'ordering': ['-request_at'],
            },
        ),
        migrations.AddField(
            model_name='capimaxaccount',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capimax.capimaxplatform'),
        ),
        migrations.AddField(
            model_name='capimaxaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capimax_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
