# Generated by Django 4.2.7 on 2025-08-20 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pronova', '0001_initial'),
        ('loans', '0002_loanapplication_certificate_generated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripartiteContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_number', models.CharField(max_length=50, unique=True)),
                ('prn_amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('usd_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loan_duration_months', models.PositiveIntegerField()),
                ('monthly_payment_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_signatures', 'Pending Signatures'), ('nova_signed', 'Nova Signed'), ('client_signed', 'Client Signed'), ('fully_executed', 'Fully Executed'), ('terminated', 'Terminated'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('nova_signature_date', models.DateTimeField(blank=True, null=True)),
                ('client_signature_date', models.DateTimeField(blank=True, null=True)),
                ('effective_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField()),
                ('termination_date', models.DateTimeField(blank=True, null=True)),
                ('termination_reason', models.TextField(blank=True)),
                ('pdf_generated', models.BooleanField(default=False)),
                ('pdf_file_path', models.CharField(blank=True, max_length=500)),
                ('capimax_contract_id', models.CharField(blank=True, max_length=255)),
                ('capimax_authorized', models.BooleanField(default=False)),
                ('capimax_authorization_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tripartite_contract', to='pronova.electroniccertificate')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tripartite_contracts', to=settings.AUTH_USER_MODEL)),
                ('loan_application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tripartite_contract', to='loans.loanapplication')),
                ('nova_signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nova_signed_contracts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContractNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('signature_required', 'Signature Required'), ('contract_executed', 'Contract Fully Executed'), ('contract_expired', 'Contract Expired'), ('amendment_requested', 'Amendment Requested'), ('payment_reminder', 'Payment Reminder'), ('capimax_update', 'Capimax Update')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('sms_sent', models.BooleanField(default=False)),
                ('action_required', models.BooleanField(default=False)),
                ('action_url', models.URLField(blank=True)),
                ('action_completed', models.BooleanField(default=False)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='contracts.tripartitecontract')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContractAmendment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amendment_number', models.CharField(max_length=50)),
                ('amendment_type', models.CharField(choices=[('loan_extension', 'Loan Term Extension'), ('payment_modification', 'Payment Modification'), ('amount_adjustment', 'Amount Adjustment'), ('capimax_change', 'Capimax Investment Change'), ('general_amendment', 'General Amendment')], max_length=30)),
                ('description', models.TextField()),
                ('changes_summary', models.JSONField(default=dict)),
                ('legal_justification', models.TextField()),
                ('approved_by_nova', models.BooleanField(default=False)),
                ('approved_by_client', models.BooleanField(default=False)),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('effective_date', models.DateTimeField(blank=True, null=True)),
                ('pdf_generated', models.BooleanField(default=False)),
                ('pdf_file_path', models.CharField(blank=True, max_length=500)),
                ('original_contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='contracts.tripartitecontract')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_amendments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ElectronicSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signer_role', models.CharField(max_length=50)),
                ('signature_type', models.CharField(choices=[('click_to_sign', 'Click to Sign'), ('drawn_signature', 'Drawn Signature'), ('uploaded_signature', 'Uploaded Signature'), ('sms_verification', 'SMS Verification'), ('email_verification', 'Email Verification')], max_length=20)),
                ('signature_data', models.TextField()),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_method', models.CharField(blank=True, max_length=50)),
                ('verification_code', models.CharField(blank=True, max_length=10)),
                ('verification_attempts', models.PositiveIntegerField(default=0)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='contracts.tripartitecontract')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('contract', 'signer')},
            },
        ),
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('contract_type', models.CharField(choices=[('loan_agreement', 'Loan Agreement'), ('tripartite_contract', 'Tripartite Contract (Nova-Client-Capimax)'), ('prn_issuance', 'PRN Issuance Agreement'), ('pledge_agreement', 'Pledge Agreement'), ('investment_authorization', 'Investment Authorization')], max_length=50)),
                ('language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic'), ('es', 'Spanish'), ('fr', 'French')], default='en', max_length=5)),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('template_content', models.TextField()),
                ('legal_text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('requires_signature', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('contract_type', 'language', 'version')},
            },
        ),
    ]
