# Generated by Django 4.2.7 on 2025-08-21 12:07

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0002_loanapplication_certificate_generated_and_more'),
        ('documents', '0002_alter_electronicsignature_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('increase', 'Loan Amount Increase'), ('settlement', 'Early Settlement'), ('deferral', 'Payment Deferral'), ('restructure', 'Loan Restructuring'), ('extension', 'Loan Extension'), ('partial_settlement', 'Partial Settlement'), ('currency_change', 'Currency Change'), ('payment_plan', 'Payment Plan Modification')], max_length=30)),
                ('request_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('reason', models.TextField(help_text='Reason for the request')),
                ('request_data', models.JSONField(default=dict, help_text='Request-specific data')),
                ('requested_amount_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Amount for increase/settlement requests', max_digits=12, null=True)),
                ('current_balance_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Current loan balance at time of request', max_digits=12, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('fee_amount_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('new_monthly_payment_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('new_final_payment_date', models.DateField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('internal_notes', models.TextField(blank=True, help_text='Internal staff notes')),
                ('customer_notes', models.TextField(blank=True, help_text='Notes visible to customer')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modification_requests', to='loans.loan')),
                ('supporting_documents', models.ManyToManyField(blank=True, help_text='Supporting documents for the request', to='documents.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan Request',
                'verbose_name_plural': 'Loan Requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='SettlementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_type', models.CharField(choices=[('full', 'Full Settlement'), ('partial', 'Partial Settlement')], default='full', max_length=20)),
                ('current_outstanding_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_monthly_payment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remaining_payments', models.IntegerField()),
                ('settlement_amount_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_amount_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('settlement_fee_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('settlement_deadline', models.DateField()),
                ('payment_method', models.CharField(default='bank_transfer', max_length=50)),
                ('total_savings_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('interest_savings_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('loan_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_details', to='requests.loanrequest')),
            ],
        ),
        migrations.CreateModel(
            name='RequestStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], max_length=20)),
                ('new_status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], max_length=20)),
                ('change_reason', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('loan_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='requests.loanrequest')),
            ],
            options={
                'verbose_name': 'Request Status History',
                'verbose_name_plural': 'Request Status Histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_type', models.CharField(choices=[('customer', 'Customer Comment'), ('staff', 'Staff Note'), ('system', 'System Message'), ('approval', 'Approval Note'), ('rejection', 'Rejection Note')], default='customer', max_length=20)),
                ('content', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Internal staff notes not visible to customer')),
                ('is_important', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachments', models.ManyToManyField(blank=True, to='documents.document')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('loan_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='requests.loanrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanIncreaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_amount_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_monthly_payment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('increase_amount_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('increase_reason', models.CharField(choices=[('business_expansion', 'Business Expansion'), ('investment_opportunity', 'Investment Opportunity'), ('emergency_expense', 'Emergency Expense'), ('debt_consolidation', 'Debt Consolidation'), ('market_opportunity', 'Market Opportunity'), ('other', 'Other')], max_length=30)),
                ('new_total_amount_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_monthly_payment_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('new_duration_months', models.IntegerField(blank=True, null=True)),
                ('processing_fee_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('income_verification_required', models.BooleanField(default=True)),
                ('additional_documents_required', models.BooleanField(default=False)),
                ('credit_check_required', models.BooleanField(default=True)),
                ('loan_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='increase_details', to='requests.loanrequest')),
            ],
        ),
        migrations.CreateModel(
            name='DeferralRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deferral_reason', models.CharField(choices=[('financial_hardship', 'Financial Hardship'), ('job_loss', 'Job Loss'), ('medical_emergency', 'Medical Emergency'), ('business_disruption', 'Business Disruption'), ('natural_disaster', 'Natural Disaster'), ('other', 'Other')], max_length=30)),
                ('requested_months', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('next_payment_due', models.DateField()),
                ('monthly_payment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_payment_start_date', models.DateField(blank=True, null=True)),
                ('new_final_payment_date', models.DateField(blank=True, null=True)),
                ('deferral_fee_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('expected_income_recovery_date', models.DateField(blank=True, null=True)),
                ('proposed_catch_up_plan', models.TextField(blank=True)),
                ('hardship_documentation_provided', models.BooleanField(default=False)),
                ('alternative_payment_plan', models.TextField(blank=True)),
                ('loan_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deferral_details', to='requests.loanrequest')),
            ],
        ),
        migrations.CreateModel(
            name='RequestApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(choices=[('initial_review', 'Initial Review'), ('financial_analysis', 'Financial Analysis'), ('risk_assessment', 'Risk Assessment'), ('management_approval', 'Management Approval'), ('final_approval', 'Final Approval')], max_length=30)),
                ('step_order', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('decision', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_approval_steps', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_approval_steps', to=settings.AUTH_USER_MODEL)),
                ('loan_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='requests.loanrequest')),
            ],
            options={
                'ordering': ['step_order'],
                'unique_together': {('loan_request', 'step_name')},
            },
        ),
    ]
