# Generated by Django 5.1.4 on 2026-05-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='id_number',
            field=models.CharField(blank=True, help_text='National ID or Passport number. Used on the Master Facility Agreement and Nova Finance Instrument.', max_length=64),
        ),
    ]
