# Generated by Django 4.2.7 on 2025-08-20 07:27

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loan_number', models.CharField(max_length=50, unique=True)),
                ('principal_amount_currency', models.DecimalField(decimal_places=8, max_digits=18)),
                ('principal_amount_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee_amount_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_payment_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('remaining_amount_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('duration_months', models.PositiveIntegerField()),
                ('payments_made', models.PositiveIntegerField(default=0)),
                ('next_payment_date', models.DateField()),
                ('final_payment_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('defaulted', 'Defaulted'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('is_invested_capimax', models.BooleanField(default=False)),
                ('capimax_investment_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('installment', 'Monthly Installment'), ('partial', 'Partial Payment'), ('full', 'Full Settlement'), ('fee', 'Processing Fee')], default='installment', max_length=20)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('gateway_response', models.JSONField(default=dict)),
                ('installment_number', models.PositiveIntegerField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='loans.loan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('increase', 'Loan Increase'), ('settlement', 'Early Settlement'), ('deferral', 'Payment Deferral'), ('transfer', 'Transfer to Another Person'), ('waiver', 'Payment Waiver'), ('extension', 'Loan Extension')], max_length=20)),
                ('description', models.TextField()),
                ('request_data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='loans.loan')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_loan_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loan_amount_currency', models.DecimalField(decimal_places=8, max_digits=18)),
                ('loan_amount_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('exchange_rate_at_application', models.DecimalField(decimal_places=8, max_digits=18)),
                ('duration_months', models.PositiveIntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('fee_percentage', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=5)),
                ('fee_amount_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_payment_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_payment_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('application_data', models.JSONField(default=dict)),
                ('approval_notes', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loans', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currencies.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='loan',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loan', to='loans.loanapplication'),
        ),
        migrations.AddField(
            model_name='loan',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currencies.currency'),
        ),
        migrations.AddField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL),
        ),
    ]
