# Generated by Django 4.2.7 on 2025-08-20 15:29

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='certificate_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='prn_amount',
            field=models.DecimalField(decimal_places=8, default=Decimal('0E-8'), max_digits=18),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='prn_issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='prn_pledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='currencies.currency'),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='duration_months',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='exchange_rate_at_application',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='fee_amount_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='fee_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.50'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_amount_currency',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_amount_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='monthly_payment_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='total_payment_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
