# Generated by Django 5.2.8 on 2026-02-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signatures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='signature_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='signature',
            name='signature_image',
            field=models.ImageField(blank=True, upload_to='signatures/'),
        ),
    ]
