# Generated by Django 5.1.4 on 2026-02-05 04:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancingApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('bronova_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('usd_equivalent', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fee_percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fee_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('repayment_period_months', models.PositiveIntegerField()),
                ('monthly_installment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_fee', 'Pending Fee Payment'), ('fee_paid', 'Fee Paid'), ('pending_signature', 'Pending Signature'), ('signed', 'Signed'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('active', 'Active'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('ack_terms', models.BooleanField(default=False)),
                ('ack_fee_non_refundable', models.BooleanField(default=False)),
                ('ack_repayment_schedule', models.BooleanField(default=False)),
                ('ack_risk_disclosure', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_applications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financing_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installment_number', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('due', 'Due'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid'), ('overdue', 'Overdue'), ('deferred', 'Deferred')], default='upcoming', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('deferred_to', models.DateField(blank=True, null=True)),
                ('financing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='financing.financingapplication')),
            ],
            options={
                'ordering': ['installment_number'],
                'unique_together': {('financing', 'installment_number')},
            },
        ),
    ]
